# frozen_string_literal: true

module TagoLine
  VERSION = "0.1.4.17"
  CALLBACK_URL = ENV["LINE_CALLBACK_URL"]
  CHANNEL_ID = ENV["LINE_CHANNEL_ID"]
  CHANNEL_SECRET = ENV["LINE_CHANNEL_SECRET"]
end
